application: chunaavitukka
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /(robots\.txt)
  static_files: \1
  upload: (robots\.txt)
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /.*
  script: ctmain.application