application: chunaavitukka
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /(robots\.txt)
  static_files: \1
  upload: (robots\.txt)
- url: /css/(.*\.woff)
  static_files: css/\1
  upload: css/(.*\.woff)
  mime_type: application/font-woff

- url: /css/(.*\.eot)
  static_files: css/\1
  upload: css/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /css/(.*\.ttf)
  static_files: css/\1
  upload: css/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images

- url: /admin/tallyupdate/
  script: ctcron.application

- url: /.*
  script: ctmain.application